Блануца 4133К (контейнеры-лодочки 1-25)
markpolyak/datasets pull request #11
Opened 2024-07-18 22:10 UTC by AshuraSaint

Добавлены файлы в датасет.

2024-07-18 22:11 UTC, AshuraSaint commented
@KleinerKaktus455

2024-07-19 07:56 UTC, KleinerKaktus455 requested changes
Прошу перенести отмеченные фотки в другую папку. В связи с переносом поправить нумерацию фоток в папках и поправить комментарий в issues с номерами (необходимо отметить, что в папке halfempty не 25, а 28 картинок). Также прошу удалить файл text.txt (другой студент по незнанию запушил его в мейн).  При возможности прошу сделать новые фотки пустых баков взамен тех, которые будут перенесены в другую директорию. Изменения смогу сегодня отревьюить быстро, чтобы не оставлять практику на допсу.

2024-07-19 07:56 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/empty/16.jpg
перенести в полупустые баки. В пустых баках не должно быть видно никакого мусора

2024-07-19 07:56 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/empty/17.jpg
перенести в полупустые баки. В пустых баках не должно быть видно никакого мусора

2024-07-19 07:56 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/empty/18.jpg
перенести в полупустые баки. В пустых баках не должно быть видно никакого мусора

2024-07-19 07:56 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/empty/23.jpg
перенести в полупустые баки. В пустых баках не должно быть видно никакого мусора

2024-07-19 15:14 UTC, KleinerKaktus455 approved these changes
Работа принята. Все сделано быстро и качественно. @markpolyak , прошу проверить личку перед выставлением оценки

2024-07-20 11:43 UTC, markpolyak commented
@KleinerKaktus455 можно мерджить?

2024-07-20 17:49 UTC, KleinerKaktus455 commented
Смержила

2024-07-20 17:49 UTC, merged