Byvalin 4133k
markpolyak/datasets pull request #12
Opened 2024-07-19 20:18 UTC by Just-Engineer-dev

Собран датасет из фотографий мусорных баков для раздельного сбора, нумерация фото от 1 до 100. Нумерация видео от 1 до 4.

2024-07-19 20:20 UTC, Just-Engineer-dev commented
@KleinerKaktus455

2024-07-20 17:47 UTC, KleinerKaktus455 requested changes
Фотографии и видео хорошие, однако было забраковано несколько изображений, объекты на которых нельзя назвать мусорными баками. Прошу заменить эти изображения новыми фотографиями. После выполнения данного условия практика будет принята

2024-07-20 17:47 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/34.jpg
Это не мусорный контейнер, а автомат по сбору бутылок

2024-07-20 17:47 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/35.jpg
Это не мусорный контейнер, а автомат по сбору бутылок

2024-07-20 17:47 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/36.jpg
Это не мусорный контейнер, а автомат по сбору бутылок

2024-07-20 17:47 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/38.jpg
Это не мусорный контейнер, а контейнер для сбора одежды для благотворительности

2024-07-20 17:47 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/39.jpg
Это не мусорный контейнер, а контейнер для сбора одежды для благотворительности

2024-07-20 17:47 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/40.jpg
Это не мусорный контейнер, а контейнер для сбора одежды для благотворительности

2024-07-20 17:47 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/41.jpg
Это не мусорный контейнер, а контейнер для сбора одежды для благотворительности

2024-07-21 14:30 UTC, Just-Engineer-dev commented
@KleinerKaktus455 Заменил изображения на новые

2024-07-22 07:18 UTC, KleinerKaktus455 approved these changes

2024-07-22 07:18 UTC, KleinerKaktus455 commented
@markpolyak , работа принята

2024-07-22 07:22 UTC, merged

2024-07-27 08:39 UTC, markpolyak commented
@Just-Engineer-dev напоминаю про отчет и инд. задание в ЛК, без них оценки в сентябре не будет

2024-08-31 13:21 UTC, Just-Engineer-dev commented
@markpolyak Загрузил отчёт и индивидуальное задание