Samsonov 4134 k
markpolyak/datasets pull request #15
Opened 2024-07-28 21:59 UTC by d1maSAM

First pull request

2024-07-29 07:04 UTC, KleinerKaktus455 requested changes
Необходимо внести правки согласно комментариям. После внесения правок прошу стегнуть

2024-07-29 07:04 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/3.jpg
это не обычный мусорный бак

2024-07-29 07:04 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/4.jpg
это не обычный мусорный бак

2024-07-29 07:04 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/5.jpg
это не обычный мусорный бак

2024-07-29 07:04 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/6.jpg
это не обычный мусорный бак

2024-07-29 07:04 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/9.jpg
это не обычный мусорный бак

2024-07-29 07:04 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/10.jpg
это не обычный мусорный бак

2024-07-29 07:04 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/11.jpg
это не обычный мусорный бак

2024-07-29 07:04 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/12.jpg
это не обычный мусорный бак

2024-07-29 07:04 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/13.jpg
это не обычный мусорный бак

2024-07-29 07:04 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/14.jpg
это не обычный мусорный бак

2024-07-29 07:04 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/15.jpg
это не обычный мусорный бак

2024-07-29 07:04 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/16.jpg
это не обычный мусорный бак

2024-07-29 07:04 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/17.jpg
это не обычный мусорный бак

2024-07-29 07:04 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/18.jpg
это не обычный мусорный бак

2024-07-29 07:04 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/19.jpg
это не обычный мусорный бак

2024-07-29 07:04 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/2.jpg
это не обычный мусорный бак

2024-07-29 07:04 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/20.jpg
это не обычный мусорный бак

2024-07-29 07:04 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/full/1.jpg
Необходимо обрезать фотографию так, чтобы на ней был полностью только центральный бак

2024-07-29 07:04 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/full/2.jpg
Необходимо обрезать фотографию так, чтобы на ней был полностью только центральный бак

2024-07-29 07:04 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/full/3.jpg
Необходимо обрезать фотографию так, чтобы на ней был полностью только центральный бак

2024-07-29 07:04 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/full/5.jpg
Фото 4 и 5 слишком похожи между собой. Необходимо заменить одну из картинок

2024-07-29 07:04 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/full/8.jpg
Фотографии 6 и 8 слишком похожи между собой. Необходимо заменить одну фотографию

2024-07-29 07:04 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/halfempty/1.jpg
Фотографии 1-3 слишком похожи между собой. Необходимо заменить 2 картинки

2024-07-29 07:04 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/video/full/1.MP4
На видео присутствуют другие мусорные баки + этот бак был на других фото. Необходимо заменить видео

2024-07-29 07:04 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/video/empty/1.MP4
На видео присутствуют другие мусорные баки. Необходимо заменить видео

2024-07-30 03:25 UTC, d1maSAM commented
Я не понял про "это не обычный мусорный бак", так он же поэтому и в 4 категории, в которой баки не подходят на стандартные  конструкции .

2024-07-30 09:16 UTC, KleinerKaktus455 commented
> Я не понял про "это не обычный мусорный бак", так он же поэтому и в 4 категории, в которой баки не подходят на стандартные конструкции .

Я забыла удалить этот пункт из описания четвертой категории. Спасибо, что сказал, задание отредачила. Эти баки относятся к лодочкам, а у тебя задача собрать обычные мусорные баки

2024-08-12 14:36 UTC, d1maSAM commented
Исправил неподходящие фото и видео

2024-08-13 18:37 UTC, KleinerKaktus455 requested changes
Все ок, вот только отмеченное видео повреждено (хотя второе загруженное норм читается плеерами) + 2 фотографии не заменены. После устранения этих замечаний работа будет принята

2024-08-13 18:37 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/19.jpg
фотка не исправлена

2024-08-13 18:37 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/20.jpg
фотка не исправлена

2024-08-13 18:37 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/video/full/1.MP4
С видео все ок? В отличие от других, оно не открывается ни на маке, ни на винде. Плееры говорят, что файл битый. Перезагрузи, пожалуйста.

2024-08-21 07:28 UTC, d1maSAM commented
Да, что-то странное с этим видео было оно у меня тоже не открылось я сейчас увидел и скачиваться нормально не хотело. Перезагрузил видео, сейчас должно открываться, фото тоже исправио

2024-08-21 16:06 UTC, KleinerKaktus455 approved these changes
@markpolyak принято, мержу
Напоминаю, что нужно загрузить доки в лк, если они еще не загружены

2024-08-21 16:06 UTC, merged