Maz 4133k
markpolyak/datasets pull request #17
Opened 2024-08-18 15:17 UTC by R031-E

Все фото и видео classic_dumpsters добавлены

2024-08-19 09:18 UTC, KleinerKaktus455 requested changes
Фотки и видео отличные, только часть фотографий нужно обрезать. Эти изображения будут использованы для обучения нейросетки, поэтому нужно обрезать (ну или постараться обрезать) фотки так, чтобы на них был видно только один бак. Допускаются "куски" других баков, но их нужно постараться минимизировать. После обрезки работа будет принята

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/empty/26.jpg
Фотку нужно обрезать, чтобы по-максимуму убрать левый бак

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/empty/27.jpg
Фотку нужно обрезать, чтобы по-максимуму убрать правый бак и не было левого

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/empty/28.jpg
Фотку нужно обрезать, чтобы по-максимуму убрать правый бак

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/empty/29.jpg
Фотку нужно обрезать, чтобы по-максимуму убрать левый и правый баки

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/empty/30.jpg
Фотку нужно обрезать, чтобы по-максимуму убрать левый и правый баки

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/empty/31.jpg
Обрезать так, чтобы в кадре был только один бак

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/empty/37.jpg
Фотку нужно обрезать, чтобы по-максимуму убрать левый и правый баки

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/empty/38.jpg
Фотку нужно обрезать, чтобы по-максимуму убрать левый бак

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/empty/40.jpg
Фотку нужно обрезать, чтобы по-максимуму убрать верхний бак

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/empty/41.jpg
Фотку нужно обрезать, чтобы по-максимуму убрать верхний бак

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/empty/43.jpg
Фотку нужно обрезать, чтобы по-максимуму убрать верхний и правый баки

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/empty/45.jpg
Фотку нужно обрезать, чтобы по-максимуму убрать верхний бак

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/empty/48.jpg
Фотку нужно обрезать, чтобы по-максимуму убрать верхний бак

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/empty/49.jpg
Фотку нужно обрезать, чтобы по-максимуму убрать верхний бак

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/empty/50.jpg
Фотку нужно обрезать, чтобы по-максимуму убрать верхний бак

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/full/27.jpg
Фотку нужно обрезать, чтобы по-максимуму убрать левый и правый баки

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/full/43.jpg
Фотку нужно обрезать, чтобы по-максимуму убрать верхний бак

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/full/44.jpg
Оставить только центральный бак. Фото обрезать

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/full/45.jpg
Оставить только центральный бак. Фото обрезать

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/full/46.jpg
Оставить только центральный бак. Фото обрезать

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/full/46.jpg
Оставить только центральный бак. Фото обрезать

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/full/48.jpg
Оставить только центральный бак. Фото обрезать

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/halfempty/26.jpg
Слева в верхнем углу есть баки. Их нужно обрезать

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/halfempty/27.jpg
Оставить только центральный бак

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/halfempty/29.jpg
Обрезать

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/halfempty/32.jpg
Обрезать

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/halfempty/34.jpg
Обрезать

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/halfempty/35.jpg
Обрезать

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/halfempty/36.jpg
Обрезать

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/halfempty/37.jpg
Подобрать правый бак. Можно слегка "задеть" центральный бак, чтобы по-максимуму удалить правый

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/halfempty/38.jpg
Обрезать

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/halfempty/42.jpg
Обрезать

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/halfempty/49.jpg
Обрезать

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/29.jpg
Обрезать

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/30.jpg
Обрезать

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/34.jpg
Обрезать

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/35.jpg
Обрезать

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/37.jpg
Обрезать

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/44.jpg
Обрезать

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/46.jpg
Обрезать

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/47.jpg
Обрезать

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/48.jpg
Обрезать

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/49.jpg
Обрезать

2024-08-19 09:18 UTC, KleinerKaktus455 commented on images/dumpsters/classic_dumpsters/photo/undefined/50.jpg
Обрезать

2024-08-19 17:37 UTC, R031-E commented
@KleinerKaktus455 обрезал все отмеченные фотки

2024-08-19 18:08 UTC, KleinerKaktus455 approved these changes

2024-08-19 18:08 UTC, KleinerKaktus455 commented
@R031-E все супер, спасибо
@markpolyak  работа принята. мержу

2024-08-19 18:08 UTC, merged

2024-08-20 05:49 UTC, markpolyak commented
@R031-E напоминаю о необходимости выложить документы в ЛК. Без них оценки в сентябре не будет

2024-08-30 16:05 UTC, R031-E commented
@markpolyak выложил отчет и индивидуальное задание в личный кабинет