Добавлены по 20 фотографий empty, halfempty, full; видео full и halfe…
markpolyak/datasets pull request #18
Opened 2024-08-20 13:45 UTC by olgabushueva

Создана папка grid_separate_waste_dumsters для сетчатых контейнеров. В нее добавлены по 20 фотографий класса Empty, Halfempty, Full; 1 видео класс Full, 1 видео класса Halfempty

2024-08-20 20:35 UTC, olgabushueva commented
@KleinerKaktus455 добавлены оставшиеся фото и видео по количеству до 104

2024-08-21 07:47 UTC, KleinerKaktus455 requested changes
Нужно обрезать несколько фотографий. После этого работа будет принята. Напоминаю, что нужно выложить документы в лк, если они еще не выложены

2024-08-21 07:47 UTC, KleinerKaktus455 commented on .gitignore
Вот это дельная вещь, спасибо)

2024-08-21 07:47 UTC, KleinerKaktus455 commented on images/dumpsters/grid_separate_waste_dumsters/photo/halfempty/26.jpeg
Фото необходимо обрезать, чтобы попробовать максимально убрать баки, находящиеся за сетчатым. Торчащими штырями наверху из сетчатого можно пожертвовать при обрезке

2024-08-21 07:47 UTC, KleinerKaktus455 commented on images/dumpsters/grid_separate_waste_dumsters/photo/halfempty/28.jpeg
Нужно обрезать, чтобы максимально убрать большой бак сзади

2024-08-21 07:47 UTC, KleinerKaktus455 commented on images/dumpsters/grid_separate_waste_dumsters/photo/halfempty/32.jpeg
Нужно обрезать, чтобы максимально убрать бак сзади

2024-08-21 07:47 UTC, KleinerKaktus455 commented on images/dumpsters/grid_separate_waste_dumsters/photo/halfempty/34.jpeg
Нужно обрезать, чтобы максимально убрать большой бак сзади

2024-08-21 07:47 UTC, KleinerKaktus455 commented on images/dumpsters/grid_separate_waste_dumsters/photo/halfempty/39.jpeg
Нужно обрезать, чтобы максимально убрать большой бак сзади

2024-08-21 07:47 UTC, KleinerKaktus455 commented on images/dumpsters/grid_separate_waste_dumsters/photo/halfempty/40.jpeg
Нужно обрезать, чтобы максимально убрать большой бак сзади

2024-08-21 07:47 UTC, KleinerKaktus455 commented on images/dumpsters/grid_separate_waste_dumsters/photo/halfempty/55.jpeg
Нужно обрезать, чтобы максимально убрать бак слева

2024-08-21 07:47 UTC, KleinerKaktus455 commented on images/dumpsters/grid_separate_waste_dumsters/photo/halfempty/58.jpeg
Нужно обрезать, чтобы максимально убрать бак сзади. Крышкой можно пожертвовать при обрезке

2024-08-21 07:47 UTC, KleinerKaktus455 commented on images/dumpsters/grid_separate_waste_dumsters/photo/halfempty/61.jpeg
Нужно обрезать, чтобы максимально убрать большой бак слева

2024-08-21 07:47 UTC, KleinerKaktus455 commented on images/dumpsters/grid_separate_waste_dumsters/photo/halfempty/62.jpeg
Нужно обрезать, чтобы максимально убрать большой бак сзади

2024-08-22 07:51 UTC, KleinerKaktus455 approved these changes
@markpolyak принято, мержу
Напоминаю, что нужно загрузить доки в лк. Без них оценки не будет(

2024-08-22 07:52 UTC, merged