Meshko 4133 k
markpolyak/datasets pull request #19
Opened 2024-08-20 18:00 UTC by yofumoru

pull request

2024-08-21 14:52 UTC, yofumoru commented
@KleinerKaktus455 добавил

2024-08-21 16:01 UTC, KleinerKaktus455 commented
@yofumoru проводить ревью не буду, тк в папках empty и halfempty не хватает фотографий. В задании указано, что необходимо собрать по 25 фотографий на каждый класс

2024-08-21 16:31 UTC, yofumoru commented
@KleinerKaktus455 в папке halfempty 50 фотографий, что на 25 больше заявленных, я это компенсировал недостатком фотографий в папке empty и full. В общей сумме фотографий хватает. Не ждать же мне специально когда будет вывоз мусора, чтобы дополнить папку empty

2024-08-21 17:23 UTC, KleinerKaktus455 commented
@yofumoru можно и подождать. Не стал писать код в рамках практики, жди, когда мусоровоз опорожнит контейнер)) И еще одна ошибка в догонку: номера фоток должны начинаться с 26ти, в комментах к issue надо было отметиться. "Компенсации" фоток работают только для заданий с баками для раздельного сбора мусора, тк такие баки - редкость. Студент до тебя же доказал, что твое задание можно мало того, что сделать, так и сделать дня за 2

2024-08-21 17:30 UTC, yofumoru commented
@KleinerKaktus455 ну извините, что мне не повезло найти пустые и полные баки, зато баков я нашел больше.

2024-08-21 17:38 UTC, KleinerKaktus455 commented
@yofumoru извинения приняты! ожидаю загрузку нужных фотографий)

2024-08-21 18:22 UTC, yofumoru commented
@KleinerKaktus455

2024-08-22 08:39 UTC, KleinerKaktus455 requested changes
Увидела сбор фотографий из интернета, что запрещено! При таком подходе к выполнению практики задание никогда не будет принято! Рекомендую напрасно не тратить ни мое, ни свое время такими попытками обмана. Информацию о нарушении правил передала М.Д.Поляку

2024-08-22 08:39 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/empty/31.jpg
Данное фото необходимо обрезать, чтобы убрать мусорные баки слева

2024-08-22 08:39 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/empty/32.jpg
Данное фото необходимо обрезать, чтобы максимально убрать мусорные баки слева

2024-08-22 08:39 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/empty/41.jpg
Фото из интернета

2024-08-22 08:39 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/empty/42.jpg
Фото из интернета

2024-08-22 08:39 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/empty/43.jpg
фото из интернета

2024-08-22 08:39 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/empty/46.jpg
фото из интернета

2024-08-22 08:39 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/empty/47.jpg
фото из интернета

2024-08-22 08:39 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/empty/48.jpg
фото из интернета

2024-08-22 08:39 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/empty/49.jpg
фото из интернета

2024-08-22 08:39 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/empty/50.jpg
фото из интернета

2024-08-22 08:39 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/full/41.jpg
фото из интернета

2024-08-22 08:39 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/full/42.jpg
из интернета

2024-08-22 08:39 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/full/43.jpg
из интернета

2024-08-22 08:39 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/full/44.jpg
из интернета

2024-08-22 08:39 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/full/45.jpg
из интернета

2024-08-22 08:39 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/full/46.jpg
из интернета

2024-08-22 08:39 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/full/47.jpg
из интернета

2024-08-22 08:39 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/full/48.jpg
из интернета

2024-08-22 08:39 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/full/49.jpg
из интернета

2024-08-22 08:39 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/full/50.jpg
из интернета

2024-08-22 08:39 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/halfempty/50.jpg
обрезать фото, чтобы убрать баки слева

2024-08-22 08:39 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/video/undefined/2.mp4
прошу перезаписать видос (или вырезать из него куски) на которых мелькает другой такой же мусорный бак

2024-08-22 08:43 UTC, KleinerKaktus455 commented
Еще в ветке продублировалось видео класса empty. Чтобы его удалить, нужно использовать команду git rm

2024-08-25 14:01 UTC, yofumoru commented
@KleinerKaktus455

2024-08-26 07:58 UTC, KleinerKaktus455 requested changes
Не приняла пару фотографий, тк они крайне похожи на другие. После того, как они будут исправлены, работа будет принята, мы на финишной прямой

2024-08-26 07:58 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/full/42.jpg
Фото слишком похоже на 41е. Прошу переснять под другим углом

2024-08-26 07:58 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/full/45.jpg
Фото слишком похоже на 41е. Прошу переснять под другим углом

2024-08-26 07:58 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/full/49.jpg
Слишком похоже на 48. Прошу переснять под другим углом

2024-08-26 15:15 UTC, yofumoru commented
@KleinerKaktus455

2024-08-27 18:25 UTC, KleinerKaktus455 commented
Про ревью не забыла, завтра посмотрю

2024-08-28 11:32 UTC, KleinerKaktus455 approved these changes

2024-08-28 11:33 UTC, KleinerKaktus455 commented
@markpolyak Принято. Напоминаю, что нужно загрузить документы в лк, если их еще нет, иначе оценки не будет

2024-09-02 20:00 UTC, markpolyak commented
@KleinerKaktus455 можно мерджить?

2024-09-03 17:46 UTC, KleinerKaktus455 commented
> @KleinerKaktus455 можно мерджить?

да, все, что заапрувила, можно

2024-09-03 17:46 UTC, merged