Oparin_4134K
markpolyak/datasets pull request #21
Opened 2024-08-21 14:41 UTC by TREMPLIX

Vineyards

2024-08-22 05:23 UTC, markpolyak requested changes
1. Необходимо удалить лишние файы, см. пометки.
2. Необходимо добавить отсутствующие файлы, еще 100 штук с расширением tiff, см. задание.
3. Все файлы *.tif и *.tiff необходимо переместить в директорию images/vineyards/subset2

После выполнения этих пунктов будет произведена проверка качества подготовленных изображений и их соответствия заданию

2024-08-22 05:23 UTC, markpolyak commented on .DS_Store
Файл нужно удалить

2024-08-22 05:23 UTC, markpolyak commented on images/.DS_Store
Файл нужно удалить

2024-08-22 11:58 UTC, TREMPLIX commented
Здравствуйте, Марк Дмитриевич!

Удалил файлы, добавил 100 недостающих файлов и переместил в другую директорию

2024-08-22 16:44 UTC, markpolyak approved these changes

2024-08-22 23:21 UTC, serg-shkviro approved these changes

2024-08-29 09:15 UTC, markpolyak approved these changes

2024-08-29 09:15 UTC, merged