vineyard_dataset_Annamuradov_4133K
markpolyak/datasets pull request #23
Opened 2024-08-26 20:08 UTC by Code-runner101

2024-08-26 20:16 UTC, Code-runner101 commented
Vineyards

2024-08-29 09:13 UTC, markpolyak requested changes
Все файлы *.tif и *.tiff необходимо переместить в директорию images/vineyards/subset3

2024-08-29 14:51 UTC, Code-runner101 commented
@markpolyak все файлы переместил в images/vineyards/subset3

2024-08-29 15:11 UTC, markpolyak commented
> @markpolyak все файлы переместил в images/vineyards/subset3

Гитхаб показывает, что файлы не перемещены, а скопированы. Теперь они сразу в двух папках. Так быть не должно

2024-08-29 15:57 UTC, Code-runner101 commented
Прошу прощения, не заметил. Исправил.

2024-09-03 09:16 UTC, serg-shkviro requested changes
На изображении должны остаться только белые линии на чёрном фоне. Быстрее всего будет пройтись кодом и закрасить все пиксели != (255,255,255) (или другое значение, смотря каким размечали) в (0,0,0)

2024-09-04 03:41 UTC, Code-runner101 commented
@serg-shkviro выгрузил новую пачку изображений с исправлениями.

2024-09-04 09:26 UTC, markpolyak approved these changes

2024-09-04 09:27 UTC, merged