Surnina 4136
markpolyak/datasets pull request #25
Opened 2024-09-01 13:35 UTC by anaaasur

Добавлены фотографии мусорок с 101 по 200 включительно в папку images/dumpsters/separate_waste_dumsters/photo. 

Добавлены видео мусорок с 5 по 9 включительно images/dumpsters/separate_waste_dumsters/video.

2024-09-01 13:56 UTC, anaaasur commented
@KleinerKaktus455, здравствуйте. Добавила фото (№101-200) и видео (№5-9) мусорок, проверьте, пожалуйста.

2024-09-02 08:05 UTC, KleinerKaktus455 requested changes
удалила ошибочный комментарий

2024-09-02 08:10 UTC, KleinerKaktus455 requested changes
Пробежалась по вашим изображениям. К сожалению, вы сделали не тот вариант: нужно было отыскать баки для раздельного сбора мусора (см фото из этого пр: https://github.com/markpolyak/datasets/tree/Byvalin_4133k/images/dumpsters/separate_waste_dumsters/photo)

2024-09-03 09:43 UTC, anaaasur commented
@KleinerKaktus455, заменила фотографии с 101 по 200, видео с 5 по 8
9 видео просто удалила, так как в задании всего 4 видео

проверьте, пожалуйста

2024-09-04 06:59 UTC, KleinerKaktus455 requested changes
Все ок, но нужно обрезать часть фото, чтобы максимально убрать посторонние баки. При обрезке не нужно повреждать основной бак в кадре. После этого практика будет принята

2024-09-04 06:59 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/118.jpg
Прошу чуть-чуть обрезать, чтобы максимально убрать сетчатый бак справа

2024-09-04 06:59 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/119.jpg
Прошу обрезать, чтобы убрать из кадра баки слева и справа

2024-09-04 06:59 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/120.jpg
Прошу обрезать, чтобы максимально убрать из кадра баки слева и справа

2024-09-04 06:59 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/121.jpg
Прошу обрезать, чтобы убрать из кадра баки слева и справа

2024-09-04 06:59 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/126.jpg
Прошу обрезать, чтобы убрать из кадра бак слева

2024-09-04 06:59 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/131.jpg
Прошу обрезать, чтобы убрать из кадра баки слева

2024-09-04 06:59 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/132.jpg
Прошу обрезать, чтобы убрать из кадра баки слева и справа

2024-09-04 06:59 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/138.jpg
Прошу обрезать, чтобы убрать из кадра баки слева

2024-09-04 06:59 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/148.jpg
Прошу обрезать, чтобы убрать из кадра баки слева и справа

2024-09-04 06:59 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/151.jpg
Прошу обрезать, чтобы убрать из кадра бак слева

2024-09-04 06:59 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/157.jpg
Прошу обрезать, чтобы убрать из кадра баки слева и справа

2024-09-04 06:59 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/158.jpg
Прошу обрезать, чтобы убрать из кадра баки слева и справа

2024-09-04 06:59 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/159.jpg
Прошу обрезать, чтобы убрать из кадра бак слева

2024-09-04 06:59 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/160.jpg
Прошу обрезать, чтобы убрать из кадра бак слева

2024-09-04 06:59 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/164.jpg
Прошу обрезать, чтобы убрать из кадра бак справа

2024-09-04 06:59 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/182.jpg
Прошу обрезать, чтобы убрать из кадра бак справа

2024-09-04 06:59 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/184.jpg
Прошу обрезать, чтобы убрать из кадра баки слева и сверху

2024-09-04 06:59 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/185.jpg
Прошу обрезать, чтобы убрать из кадра баки сверху

2024-09-04 06:59 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/186.jpg
Прошу обрезать, чтобы убрать из кадра баки сверху

2024-09-04 06:59 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/194.jpg
Прошу обрезать, чтобы убрать из кадра баки справа

2024-09-04 06:59 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/195.jpg
Прошу обрезать, чтобы убрать из кадра баки слева

2024-09-04 06:59 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/196.jpg
Прошу обрезать, чтобы убрать из кадра баки слева и сверху

2024-09-04 06:59 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/197.jpg
Прошу обрезать, чтобы убрать из кадра баки слева, сверху и справа

2024-09-04 06:59 UTC, KleinerKaktus455 commented on images/dumpsters/separate_waste_dumsters/photo/198.jpg
Прошу обрезать, чтобы убрать из кадра баки сверху и справа

2024-09-04 09:23 UTC, anaaasur commented
@KleinerKaktus455, обрезала фотографии, которые вы попросили. Проверьте, пожалуйста
(удалила необрезанные фотки, загрузила те же самые только обрезанные)

2024-09-05 07:39 UTC, KleinerKaktus455 approved these changes
@markpolyak принято
@anaaasur напоминаю, что нужно загрузить инд задание и отчет в лк, если их там еще нет

2024-09-05 07:39 UTC, merged

2024-09-09 19:24 UTC, markpolyak commented
Титульный лист отчета оформлен неверно, см. ЛК ГУАП

2024-09-09 19:41 UTC, anaaasur commented
поправила