Shageev_4131
markpolyak/datasets pull request #33
Opened 2024-09-12 16:33 UTC by SabitShageev

Шагеев С.Ш. видео 3, фото empty 51-75, фото full 51-75, фото halfempty 80-104, фото undefined 51-75. issues #8

2024-09-12 21:52 UTC, markpolyak commented
@KleinerKaktus455

2024-09-13 10:42 UTC, KleinerKaktus455 requested changes
После обрезки правка будет принята

2024-09-13 10:42 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/full/64.jpg
Прошу обрезать фотографию, чтобы убрать бак слева

2024-09-13 10:42 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/halfempty/93.jpg
прошу обрезать фотку сверху, чтобы убрать часть других баков

2024-09-13 10:42 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/halfempty/99.jpg
Прошу обрезать фотку, чтобы убрать часть мусорных баков

2024-09-13 10:42 UTC, KleinerKaktus455 commented on images/dumpsters/boat_dumpsters/photo/undefined/71.jpg
прошу обрезать фото, чтобы убрать мусорный бак справа

2024-09-15 20:24 UTC, SabitShageev commented on images/dumpsters/boat_dumpsters/photo/halfempty/93.jpg
Добрый день! Исправил, загрузил

2024-09-15 20:24 UTC, SabitShageev commented on images/dumpsters/boat_dumpsters/photo/halfempty/99.jpg
Добрый день! Исправил, загрузил

2024-09-15 20:24 UTC, SabitShageev commented on images/dumpsters/boat_dumpsters/photo/undefined/71.jpg
Добрый день! Исправил, загрузил

2024-09-15 20:24 UTC, SabitShageev commented on images/dumpsters/boat_dumpsters/photo/full/64.jpg
Добрый день! Исправил, загрузил

2024-09-16 15:57 UTC, KleinerKaktus455 approved these changes
Принято. @markpolyak

2024-09-16 15:57 UTC, merged