Samoylov 4134k
markpolyak/datasets pull request #35
Opened 2024-09-13 13:59 UTC by D1o5

#9 @KleinerKaktus455 Проверьте пожалуйста

2024-09-13 14:16 UTC, D1o5 commented
У меня немного не хватает заполненных мусорных баков, но я надеюсь, что изобилие пустых и полупустых закроет этот недостаток. Пожалуйста, практика последний долг((((

2024-09-13 15:42 UTC, KleinerKaktus455 approved these changes
@markpolyak , принято. Однако пока прошу не мержить, возможны кое-какие правки

2024-09-18 09:36 UTC, KleinerKaktus455 requested changes
Нужно переделать нумерацию, в вк намписала, а так все ок

2024-09-30 21:58 UTC, markpolyak commented
@KleinerKaktus455 мерджим, закрываем или еще нужны правки?

2024-10-06 14:16 UTC, KleinerKaktus455 approved these changes

2024-10-06 14:16 UTC, merged